### ISSUE TITLE
Failed to parse address :0

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/gtctl#194]
I got this error from frontend when using gtctl to start a baremetal cluster:

```
Error: 0: Failed to start frontend, at ../greptimedb-dev/src/cmd/src/frontend.rs:279:14
1: Failed to parse address :0
2: AddrParseError(Socket)
```

From gtctl's log, the frontend command is 
```
component 'frontend.0' binary '../target/greptimedb-dev/release/greptime' (pid '3908968') exited with error: exit status 1
args: '[--log-level=info frontend start --metasrv-addr=127.0.0.1:3002 --http-addr=:0 --rpc-addr=:0 --mysql-addr=:0 --postgres-addr=:0 --opentsdb-addr=:0 -c=../greptimedb-dev/config/frontend.example.toml]'
```

It might be caused by the default addr parameter:
```
--http-addr=:0 --rpc-addr=:0 --mysql-addr=:0 --postgres-addr=:0 --opentsdb-addr=:0
```

gtctl config file:
```yaml
cluster:
  name: mycluster # name of the cluster
  artifact:
    local: "../target/greptimedb-dev/release/greptime"
  frontend:
    replicas: 1
    config: '../greptimedb-dev/config/frontend.example.toml'
  datanode:
    replicas: 3
    rpcAddr: 0.0.0.0:14100
    mysqlAddr: 0.0.0.0:14200
    httpAddr: 0.0.0.0:14300
    config: '../greptimedb-dev/config/datanode.example.toml'
  meta:
    replicas: 1
    storeAddr: 127.0.0.1:2379
    serverAddr: 127.0.0.1:3002
    httpAddr: 0.0.0.0:14001
    config: '../greptimedb-dev/config/metasrv.example.toml'

etcd:
  artifact:
    local: "/usr/bin/etcd"
```
